// Site data — single source of truth for generator
// Pulled verbatim from NytTagTilbud_Site_Bible v1.0 (April 2026)

const SITE = {
  name: 'NytTagTilbud.com',
  domain: 'https://www.nyttagtilbud.com',
  email: 'kontakt@nyttagtilbud.com',
  owner: 'Michael Oxholm Johansen',
  cvr: '44915847',
  gtmId: 'GTM-T2WFTMGG',
  webhook: 'https://services.leadconnectorhq.com/hooks/kVDPa4Yf1J26WsoQMLhc/webhook-trigger/dc127d54-5fe2-48e9-9699-51e9b75cb1b7',
  trustpilotUrl: 'https://dk.trustpilot.com/review/nyttagtilbud.com',
  trustpilotRating: '4.0',
  trustpilotCount: 4,
  lastUpdated: 'april 2026',
  buildDate: '2026-04-15',
};

// The 15 zones — from Bible §15 Zoner
const ZONES = [
  {
    slug: 'aarhus', num: '01', name: 'Aarhus',
    title: 'Nyt Tag Tilbud Aarhus — Få 3 Gratis Tilbud',
    desc: 'Spar op til 40.000 kr. på nyt tag i Aarhus. 3 gratis tilbud fra godkendte lokale taglæggere. Svar inden 2 timer.',
    h1: 'Nyt tag tilbud Aarhus — 3 gratis tilbud',
    heroSub: 'Få 3 gratis og uforpligtende tilbud fra godkendte taglæggere i Aarhus. 2 minutter online. Svar inden 2 timer.',
    cities: ['Aarhus C', 'Viby J', 'Brabrand', 'Risskov', 'Tranbjerg', 'Hasselager'],
    postcodes: ['8000', '8200', '8220', '8240', '8260', '8310', '8361'],
    priceRange: '120.000–260.000',
    avgJob: '180.000',
    intro: 'Aarhus er Danmarks næststørste by med over 340.000 indbyggere og en usædvanlig blandet boligmasse. Fra klassiske parcelhuse i Viby J og Risskov fra 60\'erne og 70\'erne, til nyere villakvarterer i Brabrand og rækkehuse i Tranbjerg — langt de fleste tage er mellem 30 og 50 år gamle og nærmer sig naturlig udskiftning.',
    intro2: 'Den dominerende tagtype i Aarhus-området er tegltag (ca. 58%), efterfulgt af betontagsten og eternit. Mange ældre huse har fortsat bølgeeternit, som skal håndteres særligt pga. asbest. Taglæggere i Aarhus har typisk 2-4 ugers leveringstid i sommerhalvåret og 1-2 uger om vinteren.',
    spots: 2, // remaining slots for ads
  },
  {
    slug: 'aalborg', num: '02', name: 'Aalborg',
    title: 'Nyt Tag Tilbud Aalborg — 3 Gratis Tilbud',
    desc: 'Få 3 gratis tilbud på nyt tag i Aalborg fra godkendte lokale taglæggere. Spar op til 35.000 kr. Svar samme dag.',
    h1: 'Nyt tag tilbud Aalborg — 3 gratis tilbud',
    heroSub: 'Få 3 gratis tilbud fra godkendte taglæggere i Aalborg, Nørresundby og omegn. 2 minutter online. Svar inden 2 timer.',
    cities: ['Aalborg', 'Nørresundby', 'Svenstrup', 'Hjørring'],
    postcodes: ['9000', '9200', '9230', '9400', '9800'],
    priceRange: '110.000–240.000',
    avgJob: '165.000',
    intro: 'Aalborg-området dækker hele Himmerland og Vendsyssel-kysten. Byen har en høj koncentration af 70\'er- og 80\'er-parcelhuse i forstæderne mod Nørresundby, Svenstrup og Hjørring, hvor mange tage nu er modne til udskiftning efter 35-45 års brug.',
    intro2: 'Vejrklimaet langs Limfjorden og op mod Skagerrak er hårdt for tage — salt, blæst og hyppige regnskyl slider mere end i det indre Jylland. Tegltag og stålpladetag er de mest udbredte løsninger. Lokale taglæggere i Aalborg har ofte kortere leveringstid end i Aarhus og København.',
    spots: 3,
  },
  {
    slug: 'trekanten', num: '03', name: 'Trekanten',
    title: 'Nyt Tag Tilbud Trekanten — Vejle Kolding Fredericia',
    desc: 'Få 3 gratis tilbud på nyt tag i Vejle, Kolding og Fredericia. Godkendte lokale taglæggere. Spar op til 40.000 kr.',
    h1: 'Nyt tag tilbud Trekanten — 3 gratis tilbud',
    heroSub: 'Få 3 gratis tilbud fra godkendte taglæggere i Vejle, Kolding og Fredericia. 2 minutter online.',
    cities: ['Vejle', 'Kolding', 'Fredericia', 'Middelfart'],
    postcodes: ['7100', '6000', '7000', '5500'],
    priceRange: '115.000–250.000',
    avgJob: '172.000',
    intro: 'Trekantområdet består af de tre byer Vejle, Kolding og Fredericia, som tilsammen udgør Danmarks femtestørste byområde. Her er en særlig stor andel af villaer fra 50\'erne, 60\'erne og 70\'erne med oprindelige eternit- og betontagsten, hvoraf mange nu skal skiftes.',
    intro2: 'Mange huse i området har bølgeeternit med asbest, hvilket kræver særlig håndtering og autoriseret nedrivning. Vejle har en stor andel af etageejendomme og rækkehuse med flade tage, mens Fredericia og Kolding domineres af parcelhuse. De lokale taglæggere er typisk velbookede mellem april og oktober.',
    spots: 2,
  },
  {
    slug: 'odense', num: '04', name: 'Odense',
    title: 'Nyt Tag Tilbud Odense — 3 Gratis Tilbud Fyn',
    desc: 'Få 3 gratis tilbud på nyt tag i Odense og på Fyn. Godkendte lokale taglæggere. Spar op til 35.000 kr.',
    h1: 'Nyt tag tilbud Odense — 3 gratis tilbud',
    heroSub: 'Få 3 gratis tilbud fra godkendte taglæggere i Odense og på hele Fyn. Svar inden 2 timer.',
    cities: ['Odense C', 'Odense SV', 'Odense SØ', 'Kerteminde'],
    postcodes: ['5000', '5230', '5250', '5300'],
    priceRange: '105.000–235.000',
    avgJob: '160.000',
    intro: 'Odense er Danmarks tredjestørste by med over 180.000 indbyggere og et tilhørende opland på hele Fyn. Boligmassen er domineret af parcelhuse fra 60\'erne og 70\'erne i forstæder som Odense SV og SØ, samt ældre murermesterhuse i centrum og Kerteminde.',
    intro2: 'Mange tage på Fyn er oprindelige eternitplader og betontagsten med 40+ års levetid bag sig. Fynsk klima er mildt sammenlignet med Jylland, men mange tage er alligevel modne for udskiftning. Tegltag står stærkt på Fyn både æstetisk og bygningshistorisk.',
    spots: 3,
  },
  {
    slug: 'vestjylland', num: '05', name: 'Vestjylland',
    title: 'Nyt Tag Tilbud Vestjylland — Herning Esbjerg Holstebro',
    desc: 'Få 3 gratis tilbud på nyt tag i Herning, Esbjerg, Holstebro og Vestjylland. Godkendte lokale taglæggere.',
    h1: 'Nyt tag tilbud Vestjylland — 3 gratis tilbud',
    heroSub: 'Få 3 gratis tilbud fra godkendte taglæggere i Herning, Holstebro, Esbjerg og omegn.',
    cities: ['Herning', 'Holstebro', 'Esbjerg', 'Ringkøbing'],
    postcodes: ['7400', '7500', '6700', '6950'],
    priceRange: '100.000–230.000',
    avgJob: '158.000',
    intro: 'Vestjylland dækker et stort geografisk område fra Herning og Holstebro i nord til Esbjerg og Ringkøbing mod vest. Vejret er hårdt med saltholdig vind fra Vesterhavet, som særligt slider på tagflader mod vest og nord. Mange huse har robuste stålpladetage eller moderne betontagsten.',
    intro2: 'Parcelhusområderne omkring Herning og Esbjerg har en stor andel 60\'er- og 70\'er-boliger, hvor tagene nu er modne til udskiftning. Lokale taglæggere har ofte kortere leveringstider end i Østjylland, hvilket gør det oplagt at indhente tilbud i netop dette område.',
    spots: 3,
  },
  {
    slug: 'koebenhavn', num: '06', name: 'København',
    title: 'Nyt Tag Tilbud København — 3 Gratis Tilbud',
    desc: 'Få 3 gratis tilbud på nyt tag i København og på Frederiksberg. Godkendte lokale taglæggere. Spar op til 45.000 kr.',
    h1: 'Nyt tag tilbud København — 3 gratis tilbud',
    heroSub: 'Få 3 gratis tilbud fra godkendte taglæggere i København, Frederiksberg og Gentofte. Svar inden 2 timer.',
    cities: ['København C', 'Frederiksberg', 'Gentofte', 'Hvidovre'],
    postcodes: ['1000-1999', '2000', '2820', '2650'],
    priceRange: '140.000–320.000',
    avgJob: '220.000',
    intro: 'København har Danmarks tætteste boligmasse, hvor mange ejendomme er over 100 år gamle og oprindeligt tækket med tegltag. I Frederiksberg og Gentofte er mange villaer fra 1920\'erne og 30\'erne, hvor nuværende tage er enten originale eller en første udskiftning fra 70\'erne.',
    intro2: 'Tag-priser i København ligger typisk 15-25% højere end i Jylland pga. arbejdskraft, stilladsomkostninger og pladsforhold. Til gengæld er der flere specialiserede taglæggere og mere konkurrence, så tilbudsforskelle på op til 50.000 kr. er ikke usædvanlige — netop derfor er det vigtigt at sammenligne.',
    spots: 1,
  },
  {
    slug: 'nordsjaelland', num: '07', name: 'Nordsjælland',
    title: 'Nyt Tag Tilbud Nordsjælland — Hillerød Helsingør',
    desc: 'Få 3 gratis tilbud på nyt tag i Hillerød, Helsingør og Hørsholm. Godkendte lokale taglæggere i Nordsjælland.',
    h1: 'Nyt tag tilbud Nordsjælland — 3 gratis tilbud',
    heroSub: 'Få 3 gratis tilbud fra godkendte taglæggere i Hillerød, Helsingør, Hørsholm og omegn.',
    cities: ['Hillerød', 'Helsingør', 'Hørsholm', 'Fredensborg'],
    postcodes: ['3400', '3000', '2970', '3480'],
    priceRange: '135.000–310.000',
    avgJob: '210.000',
    intro: 'Nordsjælland er kendt for sine store parcelhuse og villaer — området har en af landets højeste andele af enfamiliehuse over 200 m². Mange boliger er bygget mellem 1965 og 1985, og rigtig mange tage nærmer sig nu deres 2. udskiftning.',
    intro2: 'Med hårdt nordligt klima og mange ældre bygninger er der stor efterspørgsel på erfarne taglæggere. Tegltag dominerer klart, men stålpladetag bliver hyppigere valgt pga. lang levetid og lave vedligeholdelsesomkostninger.',
    spots: 2,
  },
  {
    slug: 'vestsjaelland', num: '08', name: 'Vestsjælland',
    title: 'Nyt Tag Tilbud Vestsjælland — Roskilde Køge Holbæk',
    desc: 'Få 3 gratis tilbud på nyt tag i Roskilde, Køge, Holbæk og Vestsjælland. Godkendte lokale taglæggere.',
    h1: 'Nyt tag tilbud Vestsjælland — 3 gratis tilbud',
    heroSub: 'Få 3 gratis tilbud fra godkendte taglæggere i Roskilde, Køge, Holbæk og omegn.',
    cities: ['Roskilde', 'Køge', 'Holbæk', 'Slagelse'],
    postcodes: ['4000', '4600', '4300', '4200'],
    priceRange: '120.000–270.000',
    avgJob: '180.000',
    intro: 'Vestsjælland har en stor andel af rækkehuse og parcelhuse fra 60\'er- og 70\'er-byggeriet. I Roskilde og Køge er der mange mindre villaer på 120-160 m² med eternit- og betontagsten, som nu er modne for udskiftning efter 40+ års brug.',
    intro2: 'Tag-priser i Vestsjælland ligger midt mellem København og Jylland. Mange lokale taglæggere er mobile og dækker både Roskilde, Holbæk og Køge — det giver bedre konkurrence og typisk hurtigere leveringstider end i København.',
    spots: 3,
  },
  {
    slug: 'sydsjaelland', num: '09', name: 'Sydsjælland',
    title: 'Nyt Tag Tilbud Sydsjælland — Næstved Vordingborg',
    desc: 'Få 3 gratis tilbud på nyt tag i Næstved, Vordingborg, Stevns og Sydsjælland. Godkendte lokale taglæggere.',
    h1: 'Nyt tag tilbud Sydsjælland — 3 gratis tilbud',
    heroSub: 'Få 3 gratis tilbud fra godkendte taglæggere i Næstved, Vordingborg og på Stevns.',
    cities: ['Næstved', 'Vordingborg', 'Store Heddinge', 'Præstø'],
    postcodes: ['4700', '4760', '4660', '4720'],
    priceRange: '105.000–230.000',
    avgJob: '158.000',
    intro: 'Sydsjælland er præget af landlig bebyggelse med mange gamle landejendomme, hvor tagene oprindeligt var tegl eller bølgeeternit. I Næstved og Vordingborg findes store parcelhuskvarterer fra 70\'erne, hvor mange nu kræver nyt tag efter 45+ års levetid.',
    intro2: 'Priserne i Sydsjælland er typisk 10-15% lavere end på Nordsjælland pga. lavere lønomkostninger og kortere afstand for materialeleverancer. Mange lokale taglæggere i området har specialiseret sig i asbest-nedrivning og håndtering af gamle eternittage.',
    spots: 3,
  },
  {
    slug: 'sydhavet', num: '10', name: 'Sydhavsøerne',
    title: 'Nyt Tag Tilbud Sydhavet — Nykøbing F Maribo Rønne',
    desc: 'Få 3 gratis tilbud på nyt tag på Falster, Lolland og Bornholm. Godkendte lokale taglæggere.',
    h1: 'Nyt tag tilbud Sydhavet — 3 gratis tilbud',
    heroSub: 'Få 3 gratis tilbud fra godkendte taglæggere i Nykøbing F, Maribo, Rønne og omegn.',
    cities: ['Nykøbing F', 'Maribo', 'Rønne', 'Nakskov'],
    postcodes: ['4800', '4930', '3700', '4900'],
    priceRange: '95.000–215.000',
    avgJob: '148.000',
    intro: 'Sydhavsøerne dækker Falster, Lolland og Bornholm. Her er Danmarks ældste boligmasse med mange huse fra 1920-1960 — ofte med oprindelige tegltage eller udskiftet eternit fra 70\'erne. Mange boligejere her står overfor første eller anden tagudskiftning.',
    intro2: 'Tag-priser på Sydhavsøerne er blandt Danmarks laveste — 15-20% under landsgennemsnittet — både pga. billigere arbejdskraft og kortere afstande inden for øerne. På Bornholm er tegltag dominerende af æstetiske og bygningshistoriske grunde.',
    spots: 3,
  },
  {
    slug: 'ostjylland', num: '11', name: 'Østjylland',
    title: 'Nyt Tag Tilbud Østjylland — Randers Silkeborg Viborg',
    desc: 'Få 3 gratis tilbud på nyt tag i Randers, Silkeborg, Viborg og Østjylland. Godkendte lokale taglæggere.',
    h1: 'Nyt tag tilbud Østjylland — 3 gratis tilbud',
    heroSub: 'Få 3 gratis tilbud fra godkendte taglæggere i Randers, Silkeborg og Viborg.',
    cities: ['Randers', 'Silkeborg', 'Viborg', 'Skanderborg'],
    postcodes: ['8900', '8600', '8800', '8660'],
    priceRange: '110.000–240.000',
    avgJob: '165.000',
    intro: 'Østjylland har en særdeles stor andel af parcelhuse fra 70\'er-boom\'et, og mange af dem står nu overfor deres første store tagudskiftning. Randers, Silkeborg og Viborg er klassiske villaforstæder med dominerende betontagsten og eternit.',
    intro2: 'Lokale taglæggere i Østjylland er typisk hurtigere at booke end i Aarhus pga. lavere konkurrence om materialer og arbejdskraft. Prisniveauet ligger lidt under Aarhus, og Silkeborg-området har flere specialiserede taglæggere i tegl og stål.',
    spots: 3,
  },
  {
    slug: 'sonderjylland', num: '12', name: 'Sønderjylland',
    title: 'Nyt Tag Tilbud Sønderjylland — Aabenraa Sønderborg',
    desc: 'Få 3 gratis tilbud på nyt tag i Aabenraa, Sønderborg, Haderslev og Sønderjylland.',
    h1: 'Nyt tag tilbud Sønderjylland — 3 gratis tilbud',
    heroSub: 'Få 3 gratis tilbud fra godkendte taglæggere i Aabenraa, Sønderborg og Haderslev.',
    cities: ['Aabenraa', 'Sønderborg', 'Haderslev', 'Tønder'],
    postcodes: ['6200', '6400', '6100', '6270'],
    priceRange: '100.000–220.000',
    avgJob: '152.000',
    intro: 'Sønderjylland har en unik blandet boligmasse med både tyske og danske byggetraditioner. Mange huse i Aabenraa og Sønderborg er bygget i perioden 1950-1975 med originale tegltage, som nu er modne for udskiftning.',
    intro2: 'Prisniveauet er lavt — ca. 15% under landsgennemsnittet — og lokale taglæggere har ofte kortere leveringstid. Haderslev og Aabenraa har flere velrenommerede taglæggere, som dækker hele Sønderjylland-regionen.',
    spots: 3,
  },
  {
    slug: 'nordjylland', num: '13', name: 'Nordjylland',
    title: 'Nyt Tag Tilbud Nordjylland — Frederikshavn Hjørring',
    desc: 'Få 3 gratis tilbud på nyt tag i Frederikshavn, Hjørring, Thisted og Nordjylland.',
    h1: 'Nyt tag tilbud Nordjylland — 3 gratis tilbud',
    heroSub: 'Få 3 gratis tilbud fra godkendte taglæggere i Frederikshavn, Hjørring og Thisted.',
    cities: ['Frederikshavn', 'Hjørring', 'Thisted', 'Skagen'],
    postcodes: ['9900', '9800', '7700', '9990'],
    priceRange: '100.000–225.000',
    avgJob: '155.000',
    intro: 'Nordjylland dækker hele Vendsyssel og Thy, hvor klimaet er blandt landets mest barske. Salt, storm og frost slider hårdt på tagene, og mange huse her kræver hyppigere udskiftning end i det indre Jylland.',
    intro2: 'Stålpladetag og nyere betontagsten er populære valg pga. robusthed. Tegltag fastholder dog stadig en stærk position i Hjørring og Skagen af æstetiske grunde. Lokale taglæggere har typisk god kapacitet og konkurrencedygtige priser.',
    spots: 3,
  },
  {
    slug: 'vestfyn', num: '14', name: 'Vestfyn',
    title: 'Nyt Tag Tilbud Vestfyn — Svendborg Middelfart Assens',
    desc: 'Få 3 gratis tilbud på nyt tag på Vestfyn — Svendborg, Middelfart, Assens. Godkendte lokale taglæggere.',
    h1: 'Nyt tag tilbud Vestfyn — 3 gratis tilbud',
    heroSub: 'Få 3 gratis tilbud fra godkendte taglæggere i Svendborg, Middelfart og Assens.',
    cities: ['Svendborg', 'Middelfart', 'Assens', 'Bogense'],
    postcodes: ['5700', '5500', '5610', '5400'],
    priceRange: '100.000–220.000',
    avgJob: '152.000',
    intro: 'Vestfyn dækker de mindre fynske byer uden for Odense — Svendborg, Middelfart, Assens og Bogense. Her er mange landejendomme og mindre villaer fra 50\'erne og 60\'erne med originale tegltage og bølgeeternit, som nu skal skiftes.',
    intro2: 'Det fynske klima er mildt, og tag-priserne er blandt Danmarks laveste. Svendborg-området har en særligt høj koncentration af erfarne taglæggere med speciale i tegltag, da bygningskulturen historisk har favoriseret netop dette.',
    spots: 3,
  },
  {
    slug: 'midtsjaelland', num: '15', name: 'Midtsjælland',
    title: 'Nyt Tag Tilbud Midtsjælland — Allerød Farum',
    desc: 'Få 3 gratis tilbud på nyt tag i Allerød, Farum, Lynge og Midtsjælland. Godkendte lokale taglæggere.',
    h1: 'Nyt tag tilbud Midtsjælland — 3 gratis tilbud',
    heroSub: 'Få 3 gratis tilbud fra godkendte taglæggere i Allerød, Farum og Lynge.',
    cities: ['Allerød', 'Farum', 'Lynge', 'Birkerød'],
    postcodes: ['3450', '3520', '3540', '3460'],
    priceRange: '130.000–290.000',
    avgJob: '195.000',
    intro: 'Midtsjælland dækker de store nordjællandske villaforstæder som Allerød, Farum, Lynge og Birkerød. Her er en af landets tætteste koncentrationer af moderne enfamiliehuse fra 70\'erne og 80\'erne med oprindelige betontagsten, som nu er modne for udskiftning.',
    intro2: 'Området har høj betalingsevne og mange boligejere vælger premium-løsninger som tegltag i håndklinket stil eller stålpladetag med 50+ års garanti. Priserne er på niveau med Nordsjælland — typisk 10-15% over landsgennemsnittet.',
    spots: 2,
  },
];

// City pages — only Bible-named cities (Aarhus 5, Aalborg 2, Trekanten 3 = 10)
const CITIES = [
  // Aarhus zone
  { zone: 'aarhus', slug: 'viby', name: 'Viby J', postcode: '8260',
    intro: 'Viby J er en af Aarhus\' største forstæder med ca. 15.000 indbyggere og en boligmasse, der overvejende består af parcelhuse fra 1965-1980. Mange af disse huse har oprindelige betontagsten eller eternit, som nu er modne for udskiftning efter 40-50 års brug.',
    intro2: 'Typiske tagarealer i Viby J ligger på 110-160 m², og prisen for et nyt tegltag ligger typisk mellem 140.000 og 240.000 kr. inklusive nedrivning, undertag, lægter og montering. Lokale taglæggere i området har typisk 2-3 ugers leveringstid.' },
  { zone: 'aarhus', slug: 'brabrand', name: 'Brabrand', postcode: '8220',
    intro: 'Brabrand er en moderne forstad vest for Aarhus centrum, kendt for blandingen af 70\'er-parcelhuse og nyere rækkehuse. Området omkring Brabrand Sø har en stor andel af villaer fra 1975-1990, hvor mange nu står overfor første store tagudskiftning.',
    intro2: 'Brabrand har historisk haft mange betontagsten og enkelte eternittage. De moderne rækkehuse fra 00\'erne har typisk stålpladetag eller betontagsten med endnu 10-20 år tilbage. Priserne ligger på niveau med det øvrige Aarhus — mellem 130.000 og 230.000 kr.' },
  { zone: 'aarhus', slug: 'risskov', name: 'Risskov', postcode: '8240',
    intro: 'Risskov er en af Aarhus\' mest velhavende forstæder med over 11.000 indbyggere og en stor andel eksklusive villaer fra 1950\'erne til i dag. Mange ældre huse i Risskov har originale tegltage, som nu er 60+ år gamle og kræver udskiftning.',
    intro2: 'Boligejere i Risskov vælger ofte premium-løsninger som håndklinkede tegltag, naturskifer eller stålpladetag med lang garanti. Priserne ligger typisk 10-15% over Aarhus-gennemsnittet pga. større tagflader og mere avancerede materialer — ofte 180.000-320.000 kr.' },
  { zone: 'aarhus', slug: 'tranbjerg', name: 'Tranbjerg', postcode: '8310',
    intro: 'Tranbjerg ligger syd for Aarhus og er præget af store parcelhuskvarterer fra 1975-1995. Området er en klassisk familiefremkommen forstad med mange villaer på 140-180 m² og tilhørende carporte eller dobbeltcarporte.',
    intro2: 'De fleste tage i Tranbjerg er enten betontagsten eller stålpladetag. Tegltag er mindre udbredt, men vinder frem ved udskiftninger pga. længere levetid. Priserne for et nyt tag i Tranbjerg ligger typisk mellem 135.000 og 245.000 kr.' },
  { zone: 'aarhus', slug: 'hasselager', name: 'Hasselager', postcode: '8361',
    intro: 'Hasselager er et roligt villakvarter syd for Aarhus med en overvejende boligmasse fra 70\'erne og 80\'erne. Området er kendt for store grunde, børnevenlige veje og en tæt forbindelse til Aarhus centrum via motorvejen.',
    intro2: 'Mange huse i Hasselager har oprindelige betontagsten, som nu er 40-50 år gamle og klar til udskiftning. Tegltag og stålpladetag er de hyppigste valg ved nyudskiftning. Priserne ligger typisk på 130.000-230.000 kr.' },

  // Aalborg zone
  { zone: 'aalborg', slug: 'noerresundby', name: 'Nørresundby', postcode: '9400',
    intro: 'Nørresundby ligger på nordsiden af Limfjorden og udgør sammen med Aalborg en sammenhængende by med over 140.000 indbyggere. Området er særligt kendt for store parcelhuskvarterer fra 60\'erne og 70\'erne samt nyere rækkehus-udbygninger.',
    intro2: 'Vejrklimaet i Nørresundby er hårdt — vind og salt fra Limfjorden slider på tagene. Mange huse har stålpladetag eller robuste betontagsten. Priserne for et nyt tag ligger typisk mellem 115.000 og 235.000 kr. og lokale taglæggere har ofte 1-2 ugers leveringstid.' },
  { zone: 'aalborg', slug: 'hjoerring', name: 'Hjørring', postcode: '9800',
    intro: 'Hjørring er en af Nordjyllands største byer med ca. 25.000 indbyggere og en stor andel af klassiske parcelhuse fra 50\'erne, 60\'erne og 70\'erne. Mange tage i Hjørring er originale eller en første udskiftning, som nu skal udskiftes igen efter 40-50 år.',
    intro2: 'Tegltag står stærkt i Hjørring af æstetiske grunde, og mange ældre huse har originale håndlavede tagsten. Det hårde nordjyske vejr gør kvalitet særligt vigtigt. Priserne er typisk 10% under Aalborg — 105.000-215.000 kr.' },

  // Trekanten zone
  { zone: 'trekanten', slug: 'vejle', name: 'Vejle', postcode: '7100',
    intro: 'Vejle er med sine ca. 57.000 indbyggere en af Østjyllands største byer og en vigtig del af Trekantområdet. Byen har en meget blandet boligmasse — fra gamle byhuse med tegltag i centrum til moderne villakvarterer med betontagsten i udkanten.',
    intro2: 'Mange tage i Vejle er modne for udskiftning efter 40+ års brug. Byens bakkede terræn betyder ofte mere komplekse tagkonstruktioner, hvilket kan påvirke prisen. Typiske priser i Vejle ligger på 125.000-260.000 kr.' },
  { zone: 'trekanten', slug: 'kolding', name: 'Kolding', postcode: '6000',
    intro: 'Kolding er den største by i Trekantområdet med over 60.000 indbyggere. Byen har en særlig stor andel af parcelhuse fra 1965-1985 og en lang tradition for kvalitetshåndværk — mange af landets bedste taglæggere har base i Kolding.',
    intro2: 'Betontagsten og eternit dominerer i Koldings forstæder, mens tegltag er mere udbredt i centrum og ældre villakvarterer. Priserne ligger typisk mellem 115.000 og 245.000 kr., og konkurrencen blandt lokale taglæggere gør Kolding til en af Danmarks mere prisvenlige byer for nyt tag.' },
  { zone: 'trekanten', slug: 'fredericia', name: 'Fredericia', postcode: '7000',
    intro: 'Fredericia er kendt for sin særlige militær-historiske bymidte og de store forstadsområder, der voksede frem i 60\'erne og 70\'erne. Byen har omkring 40.000 indbyggere, og langt de fleste villaer i området har originale tage fra den oprindelige byggeperiode.',
    intro2: 'Asbestholdig bølgeeternit er stadig relativt almindeligt i Fredericia, og nedrivning skal håndteres korrekt af autoriserede taglæggere. Priserne ligger typisk på 110.000-230.000 kr., og flere lokale firmaer har specialiseret sig i asbest-nedrivning.' },
];

// The 8 blog posts — full content written in blog.js template
const BLOG_POSTS = [
  { slug: 'hvad-koster-nyt-tag-2026', keyword: 'hvad koster nyt tag', priority: 'top',
    title: 'Hvad Koster et Nyt Tag i 2026? Komplet Prisguide [Opdateret]',
    desc: 'Hvad koster et nyt tag i 2026? Se priser på tegltag, betontag, stålpladetag og eternit. Spar op til 40.000 kr. med 3 gratis tilbud.',
    h1: 'Hvad koster et nyt tag i 2026?',
    lead: 'Et nyt tag er en af de største investeringer et dansk hus kan stå overfor. I 2026 ligger prisen typisk mellem 120.000 og 280.000 kr. for et gennemsnitligt parcelhus på 120-140 m². Men materiale, tagtype og husets geometri kan trække prisen markant op eller ned. Her får du den komplette prisguide.',
    readTime: '7 min læsning' },
  { slug: 'asbest-tag-regler-2025', keyword: 'asbest tag regler', priority: 'top',
    title: 'Asbest på Taget — Regler, Priser og Nedrivning 2025',
    desc: 'Har du asbest i dit tag? Se reglerne for 2025, hvad det koster at fjerne bølgeeternit og hvordan du får lovlig nedrivning af asbesttag.',
    h1: 'Asbest på taget — regler og priser 2025',
    lead: 'Mange danske huse fra perioden 1950-1985 har stadig tag med asbestholdig bølgeeternit. Det er fortsat lovligt at have liggende, men så snart det skal skiftes, stilles der strenge krav til nedrivning og bortskaffelse. Her er reglerne for 2025 og hvad det realistisk koster.',
    readTime: '6 min læsning' },
  { slug: 'tegltag-vs-betontag', keyword: 'tegltag vs betontag', priority: 'high',
    title: 'Tegltag vs. Betontag — Hvad Skal Du Vælge? [2026 Guide]',
    desc: 'Tegltag eller betontag? Se priser, levetid, æstetik og vedligeholdelse i direkte sammenligning. Vælg den rigtige tagtype til dit hus.',
    h1: 'Tegltag vs. betontag — hvilket skal du vælge?',
    lead: 'Tegltag og betontagsten er de to mest populære tagtyper i Danmark. De ligner hinanden, men adskiller sig markant på pris, levetid, vægt og æstetik. Her får du en grundig sammenligning, så du kan vælge den tagtype, der passer bedst til dit hus og budget.',
    readTime: '5 min læsning' },
  { slug: 'hvornaar-nyt-tag', keyword: 'hvornår skal mit tag skiftes', priority: 'medium',
    title: 'Hvornår Skal Mit Tag Skiftes? 7 Tegn du Ikke Må Ignorere',
    desc: 'Er dit tag modent for udskiftning? Se de 7 vigtigste tegn på at et tag skal skiftes. Spar tusindvis ved at handle i tide.',
    h1: 'Hvornår skal mit tag skiftes? 7 tegn du ikke må ignorere',
    lead: 'Et dansk tag holder typisk mellem 40 og 60 år afhængigt af materiale. Men hvordan ved du, om det er tid til udskiftning? Her er de 7 tydeligste tegn på, at dit tag snart skal skiftes — og hvorfor du sparer penge ved at handle nu.',
    readTime: '5 min læsning' },
  { slug: 'nyt-tag-aarhus-priser', keyword: 'nyt tag aarhus pris', priority: 'medium',
    title: 'Nyt Tag Aarhus — Priser 2026 [Komplet Prisguide]',
    desc: 'Hvad koster et nyt tag i Aarhus 2026? Se priser på alle tagtyper, typiske arbejdsløn og hvordan du får 3 gratis tilbud.',
    h1: 'Nyt tag Aarhus — priser 2026',
    lead: 'I Aarhus koster et nyt tag i 2026 typisk mellem 140.000 og 260.000 kr. for et gennemsnitligt parcelhus. Men prisen varierer stærkt afhængigt af bydel, tagstørrelse og materialevalg. Her får du den komplette prisguide for Aarhus-området.',
    readTime: '6 min læsning' },
  { slug: 'bolgeeternit-pris', keyword: 'bølgeeternit pris', priority: 'medium',
    title: 'Bølgeeternit Pris 2026 — Nedrivning og Udskiftning',
    desc: 'Hvad koster nedrivning og udskiftning af bølgeeternit i 2026? Se priser på asbestsanering og nyt tag. Få 3 gratis tilbud.',
    h1: 'Bølgeeternit pris 2026 — nedrivning og udskiftning',
    lead: 'Bølgeeternit med asbest findes stadig på rigtig mange danske tage. Priser for nedrivning og udskiftning starter ved ca. 120.000 kr. og afhænger af tagareal, asbestindhold og hvilket materiale du vælger som erstatning. Her er den komplette prisoversigt.',
    readTime: '5 min læsning' },
  { slug: 'tagpap-pris', keyword: 'tagpap pris', priority: 'medium',
    title: 'Tagpap Pris 2026 — Fladt Tag og Tagpaptag [Guide]',
    desc: 'Hvad koster et nyt tagpaptag i 2026? Se priser per m², levetid, vedligeholdelse og typiske omkostninger for fladt tag.',
    h1: 'Tagpap pris 2026 — fladt tag og tagpaptag',
    lead: 'Tagpap er en populær løsning til flade tage, carporte og udestuer. I 2026 ligger prisen typisk på 700-1.100 kr. per m² inklusive nedrivning af gammel tagpap og montering af nyt. Her er prisguiden og alt du skal vide om tagpap.',
    readTime: '5 min læsning' },
  { slug: 'nyt-tag-tilskud-2026', keyword: 'nyt tag tilskud 2026', priority: 'high',
    title: 'Nyt Tag Tilskud 2026 — Komplet Guide til Energitilskud',
    desc: 'Kan du få tilskud til nyt tag i 2026? Se reglerne for håndværkerfradrag, energitilskud og Bolig+ ordningen. Spar op til 15.000 kr.',
    h1: 'Nyt tag tilskud 2026 — komplet guide',
    lead: 'Selvom nyt tag i sig selv ikke er direkte tilskudsberettiget, findes der flere ordninger i 2026, som kan give dig markant rabat — fra håndværkerfradrag til energitilskud ved samtidig efterisolering. Her er hvad du kan få refunderet.',
    readTime: '6 min læsning' },
];

module.exports = { SITE, ZONES, CITIES, BLOG_POSTS };
